/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : bigint,
  'status' : string,
  'city' : string,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : [] | [string],
  'preferredDate' : [] | [string],
  'phone' : string,
  'roofSize' : [] | [string],
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : string,
}
export interface SubmitLeadArgs {
  'city' : string,
  'name' : string,
  'email' : string,
  'message' : [] | [string],
  'preferredDate' : [] | [string],
  'phone' : string,
  'roofSize' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLead' : ActorMethod<[bigint], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitLead' : ActorMethod<[SubmitLeadArgs], bigint>,
  'updateLeadStatus' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];